version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ../ppe-flask-app:/app
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ppe
      POSTGRES_USER: ppe
      POSTGRES_PASSWORD: ppe
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
