"""added new col to frames table

Revision ID: 16e116f9eeb7
Revises: 3aae59ffe442
Create Date: 2024-11-24 14:20:39.059772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e116f9eeb7'
down_revision = '3aae59ffe442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
