"""initial schema migration

Revision ID: 3aae59ffe442
Revises: 
Create Date: 2024-11-24 14:19:33.981576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aae59ffe442'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pword', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('objects',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('cameras',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('physical_location', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('camera_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('frames',
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('frame_id')
    )
    op.create_table('frame_object',
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.frame_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], ),
    sa.PrimaryKeyConstraint('frame_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frame_object')
    op.drop_table('frames')
    op.drop_table('cameras')
    op.drop_table('objects')
    op.drop_table('companies')
    # ### end Alembic commands ###
